//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrnLiteAutoLogin.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrnLiteAutoLogin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 enable 的本地化字符串。
        /// </summary>
        internal static string ACCOUNT_ENABLE {
            get {
                return ResourceManager.GetString("ACCOUNT_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 accounts.xml 的本地化字符串。
        /// </summary>
        internal static string ACCOUNT_FILENAME {
            get {
                return ResourceManager.GetString("ACCOUNT_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 id 的本地化字符串。
        /// </summary>
        internal static string ACCOUNT_ID {
            get {
                return ResourceManager.GetString("ACCOUNT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 accountlist.cfg 的本地化字符串。
        /// </summary>
        internal static string ACCOUNT_LIST_FILENAME {
            get {
                return ResourceManager.GetString("ACCOUNT_LIST_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no 的本地化字符串。
        /// </summary>
        internal static string ACCOUNT_NO {
            get {
                return ResourceManager.GetString("ACCOUNT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 account 的本地化字符串。
        /// </summary>
        internal static string ACCOUNT_NODE {
            get {
                return ResourceManager.GetString("ACCOUNT_NODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 password 的本地化字符串。
        /// </summary>
        internal static string ACCOUNT_PASSWORD {
            get {
                return ResourceManager.GetString("ACCOUNT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 accounts 的本地化字符串。
        /// </summary>
        internal static string ACCOUNT_ROOT {
            get {
                return ResourceManager.GetString("ACCOUNT_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content Type没有设定 的本地化字符串。
        /// </summary>
        internal static string CONTENT_TYPE_NOT_SET {
            get {
                return ResourceManager.GetString("CONTENT_TYPE_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 application/x-www-form-urlencoded 的本地化字符串。
        /// </summary>
        internal static string CONTENT_TYPE1 {
            get {
                return ResourceManager.GetString("CONTENT_TYPE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://grn.cybozu.net.cn/cgi-bin/cbgrn/grn.cgi/index 的本地化字符串。
        /// </summary>
        internal static string CYBOZUSH_GRN_ADDRESS {
            get {
                return ResourceManager.GetString("CYBOZUSH_GRN_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 c=28zd4 的本地化字符串。
        /// </summary>
        internal static string CYBOZUSH_GRN_IDF {
            get {
                return ResourceManager.GetString("CYBOZUSH_GRN_IDF", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 没有选中账号！ 的本地化字符串。
        /// </summary>
        internal static string NONE_ACCOUNT {
            get {
                return ResourceManager.GetString("NONE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 autorun 的本地化字符串。
        /// </summary>
        internal static string SETTING_AUTORUN {
            get {
                return ResourceManager.GetString("SETTING_AUTORUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 setting.xml 的本地化字符串。
        /// </summary>
        internal static string SETTING_FILENAME {
            get {
                return ResourceManager.GetString("SETTING_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 settings 的本地化字符串。
        /// </summary>
        internal static string SETTING_ROOT {
            get {
                return ResourceManager.GetString("SETTING_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL没有设定 的本地化字符串。
        /// </summary>
        internal static string URL_NOT_SET {
            get {
                return ResourceManager.GetString("URL_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名没有输入，不能保存。 的本地化字符串。
        /// </summary>
        internal static string USERNAME_NOT_INPUT {
            get {
                return ResourceManager.GetString("USERNAME_NOT_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 utf-8 的本地化字符串。
        /// </summary>
        internal static string UTF8 {
            get {
                return ResourceManager.GetString("UTF8", resourceCulture);
            }
        }
    }
}
